DELETE FROM Projects;
DELETE FROM sqlite_sequence WHERE name = 'Projects';
INSERT INTO Projects (ProjectName) VALUES ("ArgusApps");
INSERT INTO Projects (ProjectName) VALUES ("Arog");
INSERT INTO Projects (ProjectName) VALUES ("BMod");
INSERT INTO Projects (ProjectName) VALUES ("BostonCollege-KPMG");
INSERT INTO Projects (ProjectName) VALUES ("Breeze");
INSERT INTO Projects (ProjectName) VALUES ("Bridgemate");
INSERT INTO Projects (ProjectName) VALUES ("BusinessDevelopment");
INSERT INTO Projects (ProjectName) VALUES ("Cybersecurity");
INSERT INTO Projects (ProjectName) VALUES ("default");
INSERT INTO Projects (ProjectName) VALUES ("DVBI");
INSERT INTO Projects (ProjectName) VALUES ("DxTera");
INSERT INTO Projects (ProjectName) VALUES ("FreshConcepts");
INSERT INTO Projects (ProjectName) VALUES ("Hivetrack");
INSERT INTO Projects (ProjectName) VALUES ("INFRA");
INSERT INTO Projects (ProjectName) VALUES ("IRIS_IFile");
INSERT INTO Projects (ProjectName) VALUES ("KPMG-Sofy");
INSERT INTO Projects (ProjectName) VALUES ("Lateral");
INSERT INTO Projects (ProjectName) VALUES ("MEDplat");
INSERT INTO Projects (ProjectName) VALUES ("Meghdoot");
INSERT INTO Projects (ProjectName) VALUES ("Resigned");
INSERT INTO Projects (ProjectName) VALUES ("Simplicate");
INSERT INTO Projects (ProjectName) VALUES ("SPH-WHO");
INSERT INTO Projects (ProjectName) VALUES ("suricata");
INSERT INTO Projects (ProjectName) VALUES ("Testing-Ubuntu");
INSERT INTO Projects (ProjectName) VALUES ("TiMS");
INSERT INTO Projects (ProjectName) VALUES ("Trainee");
INSERT INTO Projects (ProjectName) VALUES ("Upwork");
INSERT INTO Projects (ProjectName) VALUES ("Vel");
INSERT INTO Projects (ProjectName) VALUES ("Web3Dapps");
INSERT INTO Projects (ProjectName) VALUES ("WordpressProjects");
INSERT INTO Projects (ProjectName) VALUES ("Zvaluate");

SELECT * FROM Projects;
